language: node_js
node_js:
  - 0.8
  - 0.10
  - 0.11
services:
  - mysql
  - postgresql
before_script:
  - mysql < assets/mysql-test.sql
  - psql < assets/postgres-test.sql
env:
  - NODE_ENV=development MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_USER=root MYSQL_PASSWORD= MYSQL_SCHEMA=naomi_test POSTGRES_HOST=localhost POSTGRES_PORT=3306 POSTGRES_USER=root POSTGRES_PASSWORD= POSTGRES_SCHEMA=naomi_test
